language: c
os:
 - linux
 - osx
compiler:
  - gcc
  - clang
env:
  - WREN_OPTIONS="" CI_ARCHS="ci_32 ci_64"
  - WREN_OPTIONS="-DWREN_NAN_TAGGING=0" CI_ARCHS="ci_64"

jobs:
  include:
    - stage: deploy
      script: bash util/deployGHP.sh
      if: branch = master AND NOT type IN (pull_request)

# Travis VMs are 64-bit but we compile both for 32 and 64 bit. To enable the
# 32-bit builds to work, we need gcc-multilib.
addons:
  apt:
    packages:
    - gcc-multilib
    - g++-multilib
    - python3-markdown
    - ruby-sass

sudo: false # Enable container-based builds.
script: make WREN_CFLAGS=${WREN_OPTIONS} ${CI_ARCHS}
